version: '3.1'
services:
  previewsapi:
    image: chooban/ace-previews-api:latest
    volumes:
      - './acedata/:/data:ro'
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    deploy:
      restart_policy:
        condition: on-failure
  ordersapi:
    image: chooban/ace-orders-api:latest
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    deploy:
      restart_policy:
        condition: on-failure
  profilesapi:
    image: chooban/ace-profiles-api:latest
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    deploy:
      restart_policy:
        condition: on-failure
    secrets:
      - auth0_client_id
      - auth0_client_secret
