version: '3.1'
services:
  previewsapi:
    image: chooban/ace-previews-api:latest
    volumes:
      - './acedata/:/data:ro'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - back
  ordersapi:
    image: chooban/ace-orders-api:latest
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - back
  profilesapi:
    image: chooban/ace-profiles-api:latest
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    secrets:
      - auth0_client_id
      - auth0_client_secret
      - auth0_management_token
      - auth0_domain
    networks:
      - back
  bootstrapapi:
    image: chooban/ace-bootstrap-api:latest
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    secrets:
      - auth0_client_id
      - auth0_domain
    networks:
      - back
  web:
    image: nginx:1.13-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/nginx/conf.d/:/etc/nginx/conf.d/
      - ./build/:/var/www/acereact/public_html/
      #- ./sites/react/:/var/www/acereact/public_html/
      #- ./sites/acemyorder/:/var/www/acemyorder/public_html/
      - ./deployment/nginx/ssl/certs/selfsigned.crt:/etc/letsencrypt/live/amusingmonkey.co.uk/selfsigned.crt
      - ./deployment/nginx/ssl/private/selfsigned.key:/etc/letsencrypt/live/amusingmonkey.co.uk/selfsigned.key
      - piwikroot:/var/www/html/
    depends_on:
      - previewsapi
      - ordersapi
      - bootstrapapi
      - profilesapi
      - webhooks
      - piwikapp
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - front
      - back
      - hooks
      - piwikback
  webhooks:
    image: chooban/ace-volume-updater:latest
    volumes:
      - ./acedata:/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - hooks
  syslogger:
    image: balabit/syslog-ng:3.7
    volumes:
      - ./deployment/syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./deployment/syslog-ng/bin:/usr/local/bin
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - back
  piwikdb:
    image: mariadb:10.1
    volumes:
      - ./deployment/mysql/runtime/:/var/lib/mysql/
      - ./deployment/mysql/conf.d/:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-verysecurepassword}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - piwikback
  piwikapp:
    image: piwik:fpm
    depends_on:
      - piwikdb
    volumes:
      - piwikroot:/var/www/html/
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - piwikback
volumes:
  piwikroot:
secrets:
  auth0_client_id:
    external: true
  auth0_client_secret:
    external: true
  auth0_management_token:
    external: true
  auth0_domain:
    external: true
networks:
  front:
    driver: overlay
  back:
    driver: overlay
  hooks:
    driver: overlay
  piwikback:
    driver: overlay
