version: '2'
services:
  previewsapi:
    image: chooban/ace-previews-api:latest
    volumes:
      - './acedata/:/data:ro'
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
  ordersapi:
    image: chooban/ace-orders-api:latest
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
  site:
    build: .
    command: npm run devbuild
    depends_on:
      - previewsapi
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  nginx:
    image: nginx:alpine
    volumes_from:
      - site
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
