version: '2'
services:
  ace_data:
    image: chooban/ace-data-container:latest
  previewsapi:
    image: chooban/ace-previews-api:latest
    depends_on:
      - ace_data
    volumes_from:
      - ace_data:ro
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
  ordersapi:
    image: chooban/ace-orders-api:latest
    environment:
      - NODE_ENV=production
  site:
    build: .
    command: npm run devbuild
    depends_on:
      - previewsapi
      - ordersapi
    ports:
      - 3001:3000
    volumes:
      - .:/home/app/build
      - /home/app/build/node_modules
