version: '3.1'
services:
  previewsapi:
    image: chooban/ace-previews-api:latest
    ports:
      - 8100:8100
    volumes:
      - './acedata/:/data:ro'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    secrets:
      - auth0_client_id
      - auth0_client_secret
      - auth0_domain
      - auth0_management_token
    networks:
      - back
  web:
    image: nginx:1.13-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/nginx/conf.d/:/etc/nginx/conf.d/
      - ./build/:/var/www/acereact/public_html/
      - ./deployment/ssl/:/etc/letsencrypt/live/ace.rosshendry.com/
      #- ./sites/react/:/var/www/acereact/public_html/
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/conf.d/:/etc/nginx/conf.d/
      #- /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      #- /etc/letsencrypt/:/etc/letsencrypt/
      - ace_piwikroot:/var/www/html/
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    networks:
      - front
      - back
      - hooks
      - piwikback
  webhooks:
    image: chooban/ace-volume-updater:latest
    volumes:
      - ./acedata:/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - hooks
  piwikdb:
    image: mariadb:10.1
    volumes:
      - ace_mariadb:/var/lib/mysql/
      - ./deployment/mysql/conf.d/:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-verysecurepassword}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - piwikback
  piwikapp:
    image: piwik:fpm
    volumes:
      - ace_piwikroot:/var/www/html/
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    networks:
      - piwikback
volumes:
  ace_piwikroot:
    external: true
  ace_mariadb:
    external: true
secrets:
  auth0_client_id:
    external: true
  auth0_client_secret:
    external: true
  auth0_management_token:
    external: true
  auth0_domain:
    external: true
networks:
  front:
    driver: overlay
  back:
    driver: overlay
  hooks:
    driver: overlay
  piwikback:
    driver: overlay
