version: '3.1'
services:
  web:
    build: .
    environment:
      - AUTH0_ID=3ZRxcpSCqh6CnKU1zFZuWbKY0uIrfK7D
      - AUTH0_DOMAIN=acemyorder.eu.auth0.com
    volumes:
      - ./build:/var/www/acereact
