version: '3.1'
services:
  previewsapi:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
  ordersapi:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
  profilesapi:
    image: chooban/ace-profiles-api:latest
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
  web:
    build: .
    command: npm run devbuild
    environment:
      - AUTH0_ID=3ZRxcpSCqh6CnKU1zFZuWbKY0uIrfK7D
      - AUTH0_DOMAIN=acemyorder.eu.auth0.com
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
secrets:
  auth0_client_id:
    file: ./client_id.txt
  auth0_client_secret:
    file: ./client_secret.txt
