version: '3.1'
services:
  previewsapi:
    image: chooban/ace-previews-api:latest
    ports:
      - 8100:8100
    volumes:
      - './acedata/:/data:ro'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    secrets:
      - auth0_client_id
      - auth0_client_secret
      - auth0_domain
      - auth0_management_token
    networks:
      - back
  web:
    image: nginx:1.13-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/nginx/conf.d/:/etc/nginx/conf.d/
      - ./build/:/var/www/acereact/public_html/
      - ./deployment/ssl/:/etc/letsencrypt/live/ace.rosshendry.com/
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s
    networks:
      - front
      - back
secrets:
  auth0_client_id:
    external: true
  auth0_client_secret:
    external: true
  auth0_management_token:
    external: true
  auth0_domain:
    external: true
networks:
  front:
    driver: overlay
  back:
    driver: overlay
