version: '3.1'
services:
  previewsapi:
    image: chooban/ace-previews-api:latest
    volumes:
      - './acedata/:/data:ro'
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
  ordersapi:
    image: chooban/ace-orders-api:latest
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
  profilesapi:
    image: chooban/ace-profiles-api:latest
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - SECRET=
      - AUDIENCE=
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - site
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./build/:/var/www/acereact/public_html/
    deploy:
      restart_policy:
        condition: on-failure
