export const CHANGE_EVENT = 'CHANGE_EVENT'
export const GOT_ISSUES = 'GOT_ISSUES'
export const GET_ISSUES = 'GET_ISSUES'
export const GET_ISSUE = 'GET_ISSUE'
export const GOT_ISSUE = 'GOT_ISSUE'
export const CHANGED_ISSUE = 'CHOSE_ISSUE'
