/* eslint no-shadow: 0 */
import test from 'tape';

import OrderToCsv from '../OrderToCsv';

test('Order formatter', (t) => {
  t.test('Order formatter', (t) => {
    const expected = 'Previews Code,Quantity,Title,Price,Publisher,Comment\n'
      + '332/0001,1,Previews,2,DIAMOND,Flibble\n'
      + '332/0010,2,Spider-Man,2.95,Marvel,\n'
      + '332/0100,1,FCBD,0.1,Image,\n'
      + ',,Total,8.00,\n\nGenerated by Ace My Order';

    const order = [
      {
        previews: '332/0001',
        quantity: 1,
        title: 'Previews',
        price: 2.00,
        publisher: 'DIAMOND',
        comment: 'Flibble'
      },
      {
        previews: '332/0010',
        quantity: 2,
        title: 'Spider-Man',
        price: 2.95,
        publisher: 'Marvel',
        comment: ''

      },
      {
        previews: '332/0100',
        quantity: 1,
        title: 'FCBD',
        price: 0.10,
        publisher: 'Image',
        comment: ''
      }
    ];

    const csv = OrderToCsv(order);

    t.equal(csv, expected);
    t.end();
  });
});
